ETF/ETF.Web/Controllers/ETFController.cs
namespace ETF.Web.Controllers
{
    using System.Web.Mvc;

    public class EtfController : Controller
    {
        // GET: ETF
        public ActionResult Dashboard()
        {
            return this.View("_Dashboard");
        }
    }
}

ETF/ETF.Web/Controllers/FileController.cs
namespace ETF.Web.Controllers
{
    using System.Web.Mvc;

    using ETF.Web.Service.Interfaces;
    using ETF.Web.ViewModel;

    /// <summary>
    /// Controller for File Upload page
    /// </summary>
    public class FileController : Controller
    {
        private readonly IFileService fileService;

        public FileController(IFileService fileService)
        {
            this.fileService = fileService;
        }

        [HttpGet]
        public ActionResult Upload()
        {
            var viewModel = this.fileService.CreateUploadFileViewModel();

            return this.View("_Upload", viewModel);
        }

        [HttpPost]
        public ActionResult Upload(UploadFileViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                this.fileService.UploadFile(viewModel);
            }
            else
            {
                viewModel.DisplayMessage = true;
            }

            return this.View("_Upload", viewModel);
        }
    }
}

ETF/ETF.Web/Views/ETF/_Dashboard.cshtml
@{
    ViewBag.Title = "ETF Performance";
}

<h2>ETF Performance</h2>

<div class="container">
    <label for="startDate" class="sr-only">Start Date</label>
    <input type="text" id="startDate" placeholder="Start Date" />
    <br />

    <label for="startDate" class="sr-only">End Date</label>
    <input type="text" id="endDate" placeholder="End Date" />
    <br />

    <button class="btn btn-default" id="updateDates" type="submit">Update</button>
</div>

<div id="etfWeightedIndicesContainer"></div>

<h3>Stock Weighted Indices Data</h3>
<div id="stockWeightedIndicesContainer"></div>

<div id="topStocksContainer"></div>

<div id="stockReturnContainer"></div>

<link href="http://cdn.datatables.net/1.10.5/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
<script src="~/Scripts/highcharts.src.js"></script>
<script src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js"></script>

<script src="~/Scripts/app/dashboard/etfWeightedIndices.js"></script>

ETF/ETF.Web/Views/File/_Upload.cshtml
@model ETF.Web.ViewModel.UploadFileViewModel


@{
    ViewBag.Title = "Upload ETF File";
}

<h2>Upload ETF File</h2>

@if (Model.DisplayMessage)
{
    if (Model.Success)
    {
        <div class="alert alert-success">Success! File uploaded. Please visit ETF Dashboard</div>
    }
    else
    {
        <div class="alert alert-danger">Error ! File upload operation encountered a problem. Please try again</div>
    }
}

@using (Html.BeginForm("Upload", "File", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <span class="btn btn-default btn-file">
        Browse <input type="file" name="file" id="file">
    </span>

    <button class="btn btn-default" id="uploadFile" type="submit">Upload</button>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>

ETF/ETF.Web/Views/Shared/_Layout.cshtml
@using ETF.Web.Infrastructure
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ETF Dashboard", "Dashboard", "Etf", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Upload File", "Upload", "File")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ETF Dashboard</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>